# Generated by Django 5.1.4 on 2025-01-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradingviewer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=8)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='transaction',
            name='unique_transaction_id',
        ),
    ]
