# Generated by Django 5.1.4 on 2025-01-02 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tradingviewer', '0003_alter_assetdata_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssetData',
        ),
    ]
