# Generated by Django 5.1.4 on 2025-01-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradingviewer', '0004_delete_assetdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=8)),
                ('average_buy_price', models.FloatField()),
                ('average_sell_price', models.FloatField()),
                ('net', models.FloatField()),
            ],
            options={
                'db_table': 'asset_data',
            },
        ),
    ]
